env:
  - DB=sqlite

language: ruby
rvm:
  - 2.7.0

before_install:
  - gem update --system
  - gem install bundler
  - gem install rake

test:
  run: "bin/rails db:migrate RAILS_ENV=test"
  run: "rake db:create"
  run: "rake db:migrate RAILS_ENV=test"

deploy:
  provider: heroku
  api_key:
    secure: 3ceee71c-13e3-4834-87c3-8b0b8ce38c11
  app: new-blog-tim13

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec
